### ISSUE TITLE
Overview week 7-8

### ISSUE THREAD

**Issue by MathiasSJacobsen** [inf112-v20/error_brain_not_found#33]
Next steps:
- [x] Skille spill logikk og visningslogikk. ( #20 )

- [x] Able to put a player on the start position ( #29 )
    - [x] Able to move the player from that start position in the direction its suppose to. ( #32 )
    - [ ] Test the implementation. ( #23 ). 

- [x] Direction ENUM (#21 )

- [ ] Make all the boards ( #24 )

- [x] Make program cards ( #25 )
